### ISSUE TITLE
User Authentication for Management Center

### ISSUE THREAD

**Issue by taschaue** [cedalo/management-center#23]
Is there a user authentication for Management Center for the administrative backend? Background would be that not everybody can make changes on ACL etc. 

Best regards
Thomas

**Comment by cleancoderocker** [comment]
Hi Thomas,

yes, we have this on the roadmap. Stay tuned! 😊

Best regards,
Philip

**Comment by taschaue** [comment]
Hi Philip,

thanks for your answer. I had the possibility to test the Management Center and I think it is a very promising product.
I'll stay tuned.

Best regards,
Thomas

**Comment by cleancoderocker** [comment]
A login will be included in the next release. Since today it is already available in the development version.

Username and password can be configured using the `CEDALO_MC_USERNAME` and `CEDALO_MC_PASSWORD` environment variables.

![image](https://user-images.githubusercontent.com/414107/111645476-0549ce80-8801-11eb-9b2b-a352d357a62f.png)

**Comment by taschaue** [comment]
Thanks for adding this feature. Looking forward to the release ...
